### ISSUE TITLE
Add documentation to leave the queue. 

### ISSUE THREAD

**Issue by shonkaga** [CMSC-201/office-hours-bot#55]
This document should have the command for leaving the queue

**Comment by snowminc** [comment]
Heya! I believe that the master branch does not have the queue request retraction feature implemented.
If this issue is in reference of any of Eric Hamilton's classes, you'll want to refer to his branch at [feature/eric](https://github.com/CMSC-201/office-hours-bot/tree/feature/eric) for source/documentation.

[You can find the documentation at the bottom of the `student.md` file here.](https://github.com/CMSC-201/office-hours-bot/blob/feature/eric/student.md#removing-from-queue)
